# Generated by Django 4.1.5 on 2023-01-26 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
