# Generated by Django 4.1.5 on 2023-01-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_end_time_auctionlist_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='auctionlist',
            name='start_time',
        ),
    ]
