# Generated by Django 4.1.5 on 2023-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlist_id_alter_bids_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
