# Generated by Django 4.1.5 on 2023-03-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlist_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='email',
            new_name='seller_email',
        ),
    ]
