# Generated by Django 4.1.5 on 2023-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_email_auctionlist_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
